apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zwul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zwul
    app.kubernetes.io/part-of: tkrw-pr712-0075-0008-app
  name: devfile-sample-zwul
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zwul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zwul
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-zwul@sha256:c9853e03981ae258858ec4d9c362748f5be6fadc4a488513c9234e64323e0a7d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
